src/Entity/PieceJointe.php
<?php

namespace App\Entity;

use App\Repository\PieceJointeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PieceJointeRepository::class)]
class PieceJointe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_fichier = null;

    #[ORM\Column]
    private ?bool $actif = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $update_at = null;

    #[ORM\ManyToMany(targetEntity: Articles::class, mappedBy: 'piece_jointe')]
    private Collection $articles;

    #[ORM\ManyToMany(targetEntity: Commentaires::class, mappedBy: 'piece_jointe')]
    private Collection $commentaires;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->nom_fichier;
    }

    public function getNomFichier(): ?string
    {
        return $this->nom_fichier;
    }

    public function setNomFichier(string $nom_fichier): self
    {
        $this->nom_fichier = $nom_fichier;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeImmutable
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeImmutable $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    /**
     * @return Collection<int, Articles>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Articles $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->addPieceJointe($this);
        }

        return $this;
    }

    public function removeArticle(Articles $article): self
    {
        if ($this->articles->removeElement($article)) {
            $article->removePieceJointe($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->addPiecejointe($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            $commentaire->removePiecejointe($this);
        }

        return $this;
    }
}

src/Controller/AdmisController.php
<?php

namespace App\Controller;

use App\Entity\Articles;
use App\Entity\Commentaires;
use App\Entity\PieceJointe;
use App\Repository\ArticlesRepository;
use App\Repository\PieceJointeRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\Boolean;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\Type\CommentType;
use App\Repository\CommentairesRepository;
use Doctrine\DBAL\Types\DateImmutableType;
use Symfony\Component\Form\CallbackTransformer;

 #[Route('/admin'), IsGranted("ROLE_ADMIN")]  //IsGranted pour gerer les autorisaton
class AdmisController extends AbstractController
{
    #[Route('/', name: 'app_Admin')]
    public function index(): Response
    {

        return $this->render('admis/index.html.twig', [
            'controller_name' => 'AdmisController',
        ]);
    }
    #[Route('/ajoute', name: 'app_ajoute')]
    public function form(ArticlesRepository $artRepos): Response
    {
        $data=$artRepos->findAll();
        return $this->render('admis/ajoute.html.twig', [
            'donne' => $data,
        ]);
    }
    #[Route('/save', name: 'app_save')]
    public function ajoute(Request $request, ArticlesRepository $art, PieceJointeRepository $pieceJ): Response
    {
        $file=$request->files->get('piece');
        $file_name=md5(uniqid()).".".$file->guessExtension();
        $file->move('images/articles',$file_name);// permet depalcer le fichier dans notre projet
        $piece=new PieceJointe();
        $piece->setNomFichier($file_name);
        $piece->setActif(true);
        $piece->setCreatedAt(new \DateTimeImmutable());
        $piece->setUpdateAt(new \DateTimeImmutable());
        $pieceJ->save($piece,true);

        $val=$request->request->all();
        $article=new Articles();
        $article->addPieceJointe($piece);
        $article->setTitre($val['titre']);
        $article->setContenu($val['contenu']);
        $article->setCreatedAt(new \DateTimeImmutable());
        $article->setUpdatedAt(new \DateTimeImmutable());
        $article->setActif(true);
        $article->setUser($this->getUser());// recuperation de l'obejt en cours 'user'
        $art->save($article,true);
        $this->addFlash('notif', 'succes');

        
        return $this->redirectToRoute('app_Raffichage');
    }
    #[Route('/tableau', name: 'app_Raffichage')]
    public function tableau(ArticlesRepository $recuper): Response
    {
     $don=$recuper->findAll(); 
       
    return $this->render('admis/affichage.html.twig',['article'=>$don]);
    }

    #[Route('/updated/{id}', name: 'app_updated')]
    public function updated($id, ArticlesRepository $artRepos): Response
    {
        $arti_recup=$artRepos->find($id);
        
    return $this->render('admis/update.html.twig',['article_recuperer'=>$arti_recup]);
    }

    #[Route('/content/{id}', name: 'app_content')]
    public function formContent($id,Request $request, ArticlesRepository $art, EntityManagerInterface $inter, PieceJointeRepository $pieceRepos ): Response
    {
        $val=$request->request->all();
        $file=$request->files->get('piece');

            $article=$art->find($id);

            $article->setTitre($val['titre']);
            $article->setContenu($val['contenu']);
            $article->setUpdatedAt(new \DateTimeImmutable());
            $article->setActif(true);
           
          
            
            if($file !==null){
                $file_name=md5(uniqid()).".".$file->guessExtension();
                $file->move('images/articles',$file_name);
                // parcouront les piecejointe vue qu'il en exixte plusieurs(collection)
                foreach($article->getPieceJointe() as $pj){
                    $pj->setNomFichier($file_name);
                }
            }
            $inter->persist($article);
            $inter->flush();
            return $this->redirectToRoute('app_Raffichage');
        }
        
        #[Route('/deleted/{id}', name: 'app_deleted')]
        public function deleted($id, ArticlesRepository $artRepos, EntityManagerInterface $enti): Response
        {
            $article=$artRepos->find($id);
            $article->setActif(false);
            $enti->remove($article);
            $enti->flush();
        return $this->redirectToRoute('app_Raffichage');
        }    

        #[Route('/liste', name: 'app_liste')]
        public function liste(): Response
        {
            
        return $this->redirectToRoute('app_Raffichage');
        }    
       
}

templates/admis/affichage.html.twig
{% extends 'baseAdmis.html.twig' %}

{% block title %}Hello adminController!{% endblock %}

{% block body %}


<div class="example-wrapper" style="font-size:20px">
<br><br><br>
    <div class="bg-image" style="background-image: url('{{asset('/images/articles/res-1.jpg')}}'); width:auto; background-position: center; background-repeat: no-repeat; background-size: cover;">
  <br><br><br>  <br><br><br>
     
       <div class="container">
    <table class="table table-black">
        <tr class="table-danger">
            <th style="color:white">TITRE </th> 
             <th style="color:white">CONTENU</th>
             <th style="color:white">CREATED AT</th>
               <th style="color:white">UPDATED AT</th>
               <th style="color:white">ACTIF</th>
               <th style="color:white">PIECES JOINTE</th>
                <th style="color:white">ACTION</th>
                
        </tr>
          {% for i in article %}{#i represente l'article1#}
            <tr> 
                <td style="color:black">{{i.titre }}</td>
                 <td style="color:black">{{i.contenu }}</td>
                 <td style="color:black">{{i.CreatedAt|date('j-m-Y')}}</td>
                 <td style="color:black">{{i.UpdatedAt|date('j-m-Y') }}</td>
                 <td style="color:black">{{i.actif }}</td>
                 <td>
                 {% for j in i.pieceJointe %}{#i represente l'article1 associer a la piece jointe#}
                   <img src="{{asset('/images/articles/'~ j.nomFichier)}}" style="width:100px"  class="thumb-image" alt="">
                   <br><br>
                  {# <a  href="{{path('app_comment')}}"> Laisser un commentaire</a> #}
                 {% endfor %}
                 
                 </td>
                <td> <a  href="{{path('app_updated',{'id':i.id})}}" class="btn btn-black">modifier</a>
                <a onclick=" return confirm('confirme la suppresion'); " href="{{path('app_deleted',{'id':i.id})}}" class="btn btn-dark"> supprimer</a></td>
            </tr>
         {% endfor %} 
      
    </table> 
    </div>
    </div>
    <br><br> <br><br>
    <a href="{{path('app_ajoute')}}" class="btn btn-info">ajouter</a>

{% endblock %}

templates/admis/ajoute.html.twig
{% extends 'baseAdmis.html.twig' %}

{% block title %}Hello AdmisController!{% endblock %}

{% block body %}

<br><br><br><br><br><br>


<div class="bg-image" style="background-image: url('{{asset('/images/articles/blog-6.jpg')}}'); height:400px; background-position: center; background-repeat: no-repeat; background-size: cover;">
<div class="container">
 
       {% for msg in app.flashes('notif') %}
        <div class="alert alert-success">{{msg}}</div>
       {% endfor %}
    <form method='post' action="{{path('app_save')}}" enctype='multipart/form-data'> {# pour signaler au form qu'on vas envoyer les fichier binaire non texteul #}
        
         <div class="form-group">
                <label for='titre' style="color:white;font-size:50px">titre</label>
                <input type='text' name='titre' class="form-control  " />
            </div>
        <div class="form-group ">
                <label for='contenu' style="color:white; font-size:50px">contenu</label>
                <textarea name='contenu' class="form-control " > </textarea>
             </div>
            
            <div class="form-group">
                <label for='piece' style="color:white;font-size:50px">Pieces jointes</label>
                <input type='file' name='piece' class="form-control "/>
            </div>
            <br><br>
                <div class="form-group">
                <input type='submit' value='valider'  class="btn btn-primary mt-4 width=5% "/>
                </div>
                

    </form>
{% endblock %}

templates/admis/index.html.twig
{% extends 'baseAdmis.html.twig' %}


{% block title %}Hello adminController!{% endblock %}

{% block body %}
<br><br><br><br>

<div class="example-wrapper">
            <div class="bg-image" style="background-image: url('{{asset('/images/articles/blog-6.jpg')}}'); height:500px;font-size:100%;background-position: center; background-repeat: no-repeat; background-size: cover;">
        <h1 class="text-danger text-center" style="font-size:50px" ><br><br><br><br><br>ESPACE RESSERVER AUX ADMINISTRATEURS</h1>
    <div>
</div>
<br><br><br><br><br><br><br><br>
{% endblock %}

templates/admis/update.html.twig
{% extends 'baseAdmis.html.twig' %}

{% block title %}Hello AdmisController!{% endblock %}

{% block body %}


<br><br><br><br><br><br><br><br>
<div class="container">
       {% for msg in app.flashes('notif') %}
        <div class="alert alert-success">{{msg}}</div>
       {% endfor %}
    <form method='post' action="{{path('app_content',{'id':article_recuperer.id})}}" enctype='multipart/form-data'> {# pour signaler au form qu'on vas envoyer les fichier bbinaire non texteul #}
        <div class="form-group ">
                <label for='titre'>Titre</label>
                <textarea name='titre' class="form-control ">{{article_recuperer.titre}}</textarea>
             </div>
            
            <div class="form-group">
                <label for='contenu'>Contenu</label>
                <input type='text' name='contenu' class="form-control " value="{{article_recuperer.contenu}}" />
            </div>
            <div class="form-group">
                <label for='piece'>Pieces jointes</label>
                <input type='file' name='piece' class="form-control " value="{{article_recuperer.piecejointe}}"/>
            </div>
            <br><br>
                <div class="form-group">
                <input type='submit' value='update'  class="btn btn-primary"/>
                </div>
                

    </form>
{% endblock %}